package indexer

import "testing"

func TestIsGeneratedFile_GoToolchainBanner(t *testing.T) {
	content := []byte(`// Code generated by protoc-gen-go. DO NOT EDIT.
// versions: ...
// source: api.proto

package api
`)
	if !isGeneratedFile(content) {
		t.Error("Go toolchain banner should be detected")
	}
}

func TestIsGeneratedFile_GeneratedPragma(t *testing.T) {
	cases := map[string][]byte{
		"line-comment @generated": []byte("// @generated signedsource <<fe98>>\n\npackage x"),
		"block-comment @generated": []byte("/* @generated by graphql-codegen */\nexport const q = ...;\n"),
	}
	for name, content := range cases {
		t.Run(name, func(t *testing.T) {
			if !isGeneratedFile(content) {
				t.Errorf("%s should be detected", name)
			}
		})
	}
}

func TestIsGeneratedFile_HashComment(t *testing.T) {
	content := []byte(`# Generated by grpc-tools.protoc-gen-python. DO NOT EDIT.
# source: foo.proto

import grpc
`)
	if !isGeneratedFile(content) {
		t.Error("Python/grpc-tools banner should be detected")
	}
}

func TestIsGeneratedFile_HTMLBanner(t *testing.T) {
	content := []byte("<!-- Generated by docfx -->\n<html>...</html>\n")
	if !isGeneratedFile(content) {
		t.Error("HTML Generated-by banner should be detected")
	}
}

// TestIsGeneratedFile_NoFalsePositiveOnPbName pins the core promise:
// extension / filename is IRRELEVANT. A file named foo_pb.go without the
// banner must not be flagged. This is the specific false-positive that
// motivated rejecting extension-based heuristics in lib-6j7.
func TestIsGeneratedFile_NoFalsePositiveOnPbName(t *testing.T) {
	content := []byte(`package api

// Status is my hand-written type even though this file could be named foo_pb.go.
type Status struct {
	Code int
}
`)
	if isGeneratedFile(content) {
		t.Error("hand-written file without banner must not be flagged as generated")
	}
}

// TestIsGeneratedFile_CRLF exercises Windows line endings — the regex
// anchors wouldn't match raw \r\n lines, so the fallback normalisation
// must kick in.
func TestIsGeneratedFile_CRLF(t *testing.T) {
	content := []byte("// Code generated by stringer. DO NOT EDIT.\r\n\r\npackage x\r\n")
	if !isGeneratedFile(content) {
		t.Error("CRLF-encoded banner should still be detected")
	}
}

// TestIsGeneratedFile_OnlyScansHead pins that banners buried past the 1 KiB
// scan window are NOT detected — the conservative scan is intentional so
// the cost stays bounded on huge files.
func TestIsGeneratedFile_OnlyScansHead(t *testing.T) {
	// 1.5 KiB of padding before the banner puts it out of the window.
	padding := make([]byte, 1500)
	for i := range padding {
		padding[i] = ' '
	}
	content := append(padding, []byte("\n// Code generated by xyz. DO NOT EDIT.\n")...)
	if isGeneratedFile(content) {
		t.Error("banner past the scan window must not be detected")
	}
}

// TestIsGeneratedFile_UTF8BOM pins that a leading UTF-8 BOM is stripped
// before banner matching — Windows / .NET codegen tools frequently prepend
// the BOM and would otherwise defeat the `^//` regex anchor.
func TestIsGeneratedFile_UTF8BOM(t *testing.T) {
	bom := []byte{0xEF, 0xBB, 0xBF}
	cases := [][]byte{
		append(bom, []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage x\n")...),
		append(bom, []byte("// @generated\n\nexport const q = 1;\n")...),
		append(bom, []byte("# Generated by sqlc. DO NOT EDIT.\n\nimport sqlite3\n")...),
	}
	for i, content := range cases {
		if !isGeneratedFile(content) {
			t.Errorf("case %d: BOM-prefixed banner should be detected; content=%q", i, content)
		}
	}
}

func TestIsGeneratedFile_EmptyAndShort(t *testing.T) {
	if isGeneratedFile(nil) {
		t.Error("nil content must return false")
	}
	if isGeneratedFile([]byte("")) {
		t.Error("empty content must return false")
	}
	// A very short file (no banner possible) just returns false.
	if isGeneratedFile([]byte("x")) {
		t.Error("one-byte content must return false")
	}
}

// TestIsGeneratedFile_RequiresFullSentinel pins that partial matches of the
// banner don't trip detection — "Code generated" on its own without the "DO
// NOT EDIT." terminator is an English sentence, not a banner. This catches
// hand-written commentary like "// Code generated by this function".
func TestIsGeneratedFile_RequiresFullSentinel(t *testing.T) {
	cases := []string{
		"// Code generated by the user reviewing this PR.\n",
		"// Generated in the obvious way.\n",
		"# Generated means produced, in this context.\n",
	}
	for _, c := range cases {
		if isGeneratedFile([]byte(c)) {
			t.Errorf("partial match should not be detected: %q", c)
		}
	}
}
