package indexer

import (
	"bytes"
	"regexp"
)

// generatedBannerBytes is how many leading bytes of a file the banner scanner
// reads. Most generator tools place the banner on line 1 (or within the first
// few lines after a leading comment header). 1 KiB comfortably covers a 5-10
// line banner in any encoding we care about, even with indented comments and
// CRLF line endings.
const generatedBannerBytes = 1024

// generatedBannerPatterns is a conservative allowlist of regular expressions
// matching the canonical "generated file" banners emitted by widely-used code
// generators. Matching is against the first ~1 KiB of file content, not
// filename — a hand-written `foo_pb.go` without the banner is NOT skipped,
// so false positives from extension heuristics don't happen.
//
// Extend only with evidence: a tool whose convention is documented and whose
// output is genuinely uneditable. Narrow regexes beat broad ones — we'd
// rather miss an exotic generator than misclassify a hand-written file.
var generatedBannerPatterns = []*regexp.Regexp{
	// Go toolchain — protoc-gen-go, stringer, mockgen, gqlgen, etc. The
	// exact spec is in cmd/go/internal/generate (Go stdlib).
	regexp.MustCompile(`(?m)^// Code generated .+ DO NOT EDIT\.\s*$`),

	// Facebook/Meta — Buck, signedsource, graphql-codegen, Relay.
	regexp.MustCompile(`(?m)^// @generated(\s|$)`),
	regexp.MustCompile(`(?m)^/\* @generated(\s|\*/)`),

	// Python / Ruby / shell generators — grpc-tools, sqlc, protoc-python.
	regexp.MustCompile(`(?m)^# Generated by .+\. DO NOT EDIT\.\s*$`),

	// HTML / XML / SVG codegen.
	regexp.MustCompile(`(?m)^<!-- Generated by .+ -->\s*$`),
}

// isGeneratedFile reports whether content's leading window matches any of the
// canonical generated-file banner patterns. Content longer than
// generatedBannerBytes is truncated for matching — we don't pay the cost of
// scanning a large file end-to-end for a banner that lives at the top.
//
// Nil or empty content returns false: empty files are nothing but also
// nothing to index, and the walker handles "no handler" / "zero size" via
// other mechanisms.
func isGeneratedFile(content []byte) bool {
	if len(content) == 0 {
		return false
	}
	// Strip a leading UTF-8 BOM. Windows / .NET codegen tools (T4, Razor,
	// CSHTML, PowerShell scripts) frequently prepend the BOM; the regex
	// anchor `^//` then fails at byte 0 because the line starts with
	// `\xEF\xBB\xBF` instead of `//`. Skip past the BOM so the anchor
	// lines up with the actual banner.
	if bytes.HasPrefix(content, []byte{0xEF, 0xBB, 0xBF}) {
		content = content[3:]
	}

	// CRLF normalisation must happen BEFORE window truncation. If we
	// truncated first and the window ended at byte 1023 with a bare `\r`
	// whose `\n` sat at byte 1024, ReplaceAll(\r\n, \n) wouldn't see the
	// pair, leaving a bare `\r` that breaks the `(?m)^...$` anchor. Only
	// allocate a normalised copy when the content actually contains \r.
	scan := content
	if bytes.IndexByte(scan, '\r') >= 0 {
		scan = bytes.ReplaceAll(scan, []byte("\r\n"), []byte("\n"))
	}
	window := scan
	if len(window) > generatedBannerBytes {
		window = scan[:generatedBannerBytes]
	}

	for _, p := range generatedBannerPatterns {
		if p.Match(window) {
			return true
		}
	}
	return false
}
