package config

import "github.com/spf13/viper"

type Config struct {
	DocsDir          string          `mapstructure:"docs_dir"`
	DBPath           string          `mapstructure:"db_path"`
	Embedding        EmbeddingConfig `mapstructure:"embedding"`
	Chunking         ChunkingConfig  `mapstructure:"chunking"`
	Office           OfficeConfig    `mapstructure:"office"`
	PDF              PDFConfig       `mapstructure:"pdf"`
	Graph            GraphConfig     `mapstructure:"graph"`
	Python           PythonConfig    `mapstructure:"python"`
	CodeFilePatterns []string        `mapstructure:"code_file_patterns"`
	ExcludePatterns  []string        `mapstructure:"exclude_patterns"`

	// ProjectRoot is the absolute path of the workspace root (the directory
	// containing .librarian/). Populated by cmd/root.go after workspace.Find()
	// succeeds. The graph pass walks this path. Empty disables the graph pass —
	// lets tests that operate without a workspace still run the docs pass.
	ProjectRoot string `mapstructure:"-"`
}

// GraphConfig controls the code-graph pass. Separate from the docs pass so the
// graph can cover every source file in the project while search_docs / the
// knowledge base stays scoped to docs_dir.
type GraphConfig struct {
	// HonorGitignore skips files matched by .gitignore (root + nested, git
	// layered semantics). Default true; each sub-project's own .gitignore
	// covers its build outputs for free.
	HonorGitignore bool `mapstructure:"honor_gitignore"`

	// DetectGenerated skips files whose first ~1 KiB contains a canonical
	// "generated file" banner (Go toolchain's `// Code generated ... DO NOT
	// EDIT.`, Meta's `// @generated`, grpc-tools' `# Generated by …`,
	// HTML/XML `<!-- Generated by ... -->`). Default true. Banner matching
	// is content-based, not extension-based, so a hand-written file named
	// `foo_pb.go` without the banner is NOT skipped.
	DetectGenerated bool `mapstructure:"detect_generated"`

	// ExcludePatterns stack on top of the built-in graph-pass default excludes
	// (.git/, .librarian/, node_modules/, vendor/, target/, build/, dist/, …).
	ExcludePatterns []string `mapstructure:"exclude_patterns"`

	// Roots restricts the graph walk to these subdirectories (relative to
	// ProjectRoot). Empty = walk the whole workspace root. Useful for
	// monorepos where only a slice of the repo is relevant to the current task.
	Roots []string `mapstructure:"roots"`

	// MaxWorkers caps the goroutines the graph pass uses. 0 (default) auto-
	// picks based on measured per-file wall time (samples the first few
	// files serially, then scales workers to the cost profile); 1 forces
	// serial; N>1 uses a fixed pool. SQLite writes serialize via the
	// connection mutex, so values above ~8 give diminishing returns.
	MaxWorkers int `mapstructure:"max_workers"`

	// ProgressMode overrides the graph pass's progress reporting. Empty
	// (default) auto-selects based on file count + whether stdout is a
	// terminal. Valid values: "verbose" (per-file line), "quiet"
	// (heartbeat every N files), "bar" (single-line rewriting progress
	// bar). Used by the CLI `--verbose` / `--quiet` flags; set here as a
	// convenience for users who always want CI runs to stay quiet without
	// relying on TTY auto-detection.
	ProgressMode string `mapstructure:"progress_mode"`
}

type EmbeddingConfig struct {
	Provider string `mapstructure:"provider"`
	Model    string `mapstructure:"model"`
	APIKey   string `mapstructure:"api_key"`
	BaseURL  string `mapstructure:"base_url"`
	// BatchSize caps the number of texts per EmbedBatch API call. 0 (default)
	// resolves to 100 inside each provider constructor; values above the
	// provider's documented max are silently clamped down. This is the
	// ceiling, not a demand.
	BatchSize int `mapstructure:"batch_size"`
}

type ChunkingConfig struct {
	MaxTokens    int `mapstructure:"max_tokens"`
	OverlapLines int `mapstructure:"overlap_lines"`
	MinTokens    int `mapstructure:"min_tokens"`
}

// OfficeConfig controls DOCX/XLSX/PPTX conversion. XLSXMaxRows / XLSXMaxCols
// bound huge spreadsheet-as-database sheets; IncludeSpeakerNotes toggles
// whether PPTX notes-slide text lands in the generated markdown.
type OfficeConfig struct {
	XLSXMaxRows         int  `mapstructure:"xlsx_max_rows"`
	XLSXMaxCols         int  `mapstructure:"xlsx_max_cols"`
	IncludeSpeakerNotes bool `mapstructure:"include_speaker_notes"`
}

// PDFConfig controls PDF ingestion. MaxPages bounds how many pages the
// handler extracts from a single PDF; 0 means unlimited. Large books with
// thousands of pages can dominate the index otherwise.
type PDFConfig struct {
	MaxPages int `mapstructure:"max_pages"`
}

// PythonConfig controls Python-specific indexing behaviour. Today only the
// relative-import resolver consumes it; future Python-specific knobs land here.
type PythonConfig struct {
	// SrcRoots lists directories (relative to ProjectRoot) whose immediate
	// children are top-level Python packages. Files under a listed prefix
	// skip the __init__.py walk and anchor at the src_root boundary — covers
	// PEP 420 namespace packages and src-layout projects. Example:
	//   python.src_roots: ["src"]   → src/mypkg/sub/a.py has package mypkg.sub
	//
	// The indexer additionally auto-detects src_roots from pyproject.toml at
	// the project root (setuptools packages.find.where, Poetry packages[].from,
	// and Hatch build.targets.wheel.packages parent dirs). Explicit entries
	// here are merged with auto-detected ones — explicit first, auto-detect
	// appended, deduped on cleaned absolute path.
	//
	// Empty (default) + no pyproject.toml: fall back to __init__.py walk,
	// then a virtual directory package as last resort. Prefixes match after
	// filepath.Clean; src_roots themselves are not recursive — only files
	// under an immediate child of the listed directory are resolved by this
	// rule.
	SrcRoots []string `mapstructure:"src_roots"`
}

func Load() *Config {
	cfg := &Config{
		DocsDir: "docs",
		DBPath:  ".librarian/librarian.db",
		Embedding: EmbeddingConfig{
			Provider: "gemini",
		},
		Chunking: ChunkingConfig{
			MaxTokens:    512,
			OverlapLines: 3,
			MinTokens:    50,
		},
		Office: OfficeConfig{
			XLSXMaxRows:         100,
			XLSXMaxCols:         50,
			IncludeSpeakerNotes: true,
		},
		PDF: PDFConfig{
			MaxPages: 0,
		},
		Graph: GraphConfig{
			HonorGitignore:  true,
			DetectGenerated: true,
		},
		CodeFilePatterns: []string{"*.go", "*.ts", "*.py", "*.rs", "*.java", "*.rb"},
		ExcludePatterns:  []string{"node_modules/**", ".git/**", "vendor/**"},
	}

	viper.Unmarshal(cfg)

	// Restore bool defaults for GraphConfig after Unmarshal. If the user's
	// config.yaml has a `graph:` section that omits these keys, mapstructure
	// decodes the absent value as `false` and clobbers the `true` default
	// we set above. Each IsSet check reinstates the default when the user
	// didn't express an opinion.
	if !viper.IsSet("graph.honor_gitignore") {
		cfg.Graph.HonorGitignore = true
	}
	if !viper.IsSet("graph.detect_generated") {
		cfg.Graph.DetectGenerated = true
	}

	if dbPath := viper.GetString("db_path"); dbPath != "" {
		cfg.DBPath = dbPath
	}

	// Fall back to default if no db_path was set via config, env, or flag
	if cfg.DBPath == "" {
		cfg.DBPath = ".librarian/librarian.db"
	}

	return cfg
}
