package config

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/viper"
)

type Config struct {
	// DocsDir is the legacy single-directory alias. DEPRECATED: prefer DocDirs.
	// Kept for backward compatibility — existing configs with `docs_dir: docs`
	// continue working unchanged. When DocDirs is non-empty, DocsDir is ignored.
	// Use ResolvedDocDirs() for all read paths instead of accessing this field
	// directly.
	DocsDir string `mapstructure:"docs_dir"`

	// DocDirs is the canonical multi-directory list of docs trees to index.
	// Supersedes DocsDir when non-empty. Entries are relative to ProjectRoot
	// (or CWD if ProjectRoot is empty). Use ResolvedDocDirs() to get the
	// cleaned, de-duplicated list with fallback logic applied.
	DocDirs          []string            `mapstructure:"doc_dirs"`
	DBPath           string              `mapstructure:"db_path"`
	Embedding        EmbeddingConfig     `mapstructure:"embedding"`
	Rerank           RerankConfig        `mapstructure:"rerank"`
	Summarization    SummarizationConfig `mapstructure:"summarization"`
	Chunking         ChunkingConfig      `mapstructure:"chunking"`
	Office           OfficeConfig        `mapstructure:"office"`
	PDF              PDFConfig           `mapstructure:"pdf"`
	Graph            GraphConfig         `mapstructure:"graph"`
	Search           SearchConfig        `mapstructure:"search"`
	Python           PythonConfig        `mapstructure:"python"`
	Analytics        AnalyticsConfig     `mapstructure:"analytics"`
	CodeFilePatterns []string            `mapstructure:"code_file_patterns"`
	ExcludePatterns  []string            `mapstructure:"exclude_patterns"`

	// ProjectRoot is the absolute path of the workspace root (the directory
	// containing .librarian/). Populated by cmd/root.go after workspace.Find()
	// succeeds. The graph pass walks this path. Empty disables the graph pass —
	// lets tests that operate without a workspace still run the docs pass.
	ProjectRoot string `mapstructure:"-"`
}

// GraphConfig controls the code-graph pass. Separate from the docs pass so the
// graph can cover every source file in the project while search_docs / the
// knowledge base stays scoped to docs_dir.
type GraphConfig struct {
	// Enabled controls whether the code-graph pass runs at all. Default true.
	// Set to false for a docs-only workspace (search_docs / get_context still
	// work; neighbors / path / explain / report have no data). Honored at
	// index time alongside the per-run --skip-graph flag — either one
	// suppresses the graph pass.
	Enabled bool `mapstructure:"enabled"`

	// HonorGitignore skips files matched by .gitignore (root + nested, git
	// layered semantics). Default true; each sub-project's own .gitignore
	// covers its build outputs for free.
	HonorGitignore bool `mapstructure:"honor_gitignore"`

	// DetectGenerated skips files whose first ~1 KiB contains a canonical
	// "generated file" banner (Go toolchain's `// Code generated ... DO NOT
	// EDIT.`, Meta's `// @generated`, grpc-tools' `# Generated by …`,
	// HTML/XML `<!-- Generated by ... -->`). Default true. Banner matching
	// is content-based, not extension-based, so a hand-written file named
	// `foo_pb.go` without the banner is NOT skipped.
	DetectGenerated bool `mapstructure:"detect_generated"`

	// ExcludePatterns stack on top of the built-in graph-pass default excludes
	// (.git/, .librarian/, node_modules/, vendor/, target/, build/, dist/, …).
	ExcludePatterns []string `mapstructure:"exclude_patterns"`

	// Roots restricts the graph walk to these subdirectories (relative to
	// ProjectRoot). Empty = walk the whole workspace root. Useful for
	// monorepos where only a slice of the repo is relevant to the current task.
	Roots []string `mapstructure:"roots"`

	// MaxWorkers caps the goroutines the graph pass uses. 0 (default) auto-
	// picks based on measured per-file wall time (samples the first few
	// files serially, then scales workers to the cost profile); 1 forces
	// serial; N>1 uses a fixed pool. SQLite writes serialize via the
	// connection mutex, so values above ~8 give diminishing returns.
	MaxWorkers int `mapstructure:"max_workers"`

	// ProgressMode overrides the graph pass's progress reporting. Empty
	// (default) auto-selects based on file count + whether stdout is a
	// terminal. Valid values: "verbose" (per-file line), "quiet"
	// (heartbeat every N files), "bar" (single-line rewriting progress
	// bar). Used by the CLI `--verbose` / `--quiet` flags; set here as a
	// convenience for users who always want CI runs to stay quiet without
	// relying on TTY auto-detection.
	ProgressMode string `mapstructure:"progress_mode"`

	// TestEdges controls heuristic test-to-subject-under-test edge emission.
	TestEdges TestEdgesConfig `mapstructure:"test_edges"`
}

// TestEdgesConfig controls the path-convention pass that emits file→file edges
// with Kind='tests' from test files to their likely subject files.
type TestEdgesConfig struct {
	// Enabled enables the heuristic. Default true.
	Enabled bool `mapstructure:"enabled"`
}

// SummarizationConfig controls optional per-chunk summary generation at index
// time. When Provider is empty or "disabled", summarization is skipped and
// doc_chunks.summary stays empty. Gemini flash and OpenAI haiku-class models
// work well here; configure a cheaper model than embedding where possible.
type SummarizationConfig struct {
	Provider string `mapstructure:"provider"` // "gemini", "openai", "" or "disabled"
	Model    string `mapstructure:"model"`
	APIKey   string `mapstructure:"api_key"`
	BaseURL  string `mapstructure:"base_url"` // for openai-compatible providers
}

// RerankConfig controls optional cross-encoder reranking at query time.
// When Provider is empty (default), reranking is disabled and SearchChunks
// behaves identically to today. Two backends are supported:
//   - "onnx": in-process ONNX Runtime, no external server. Pull weights first
//     with `librarian models pull` (or `librarian init --with-reranker`).
//   - "openai": any OpenAI-compatible /rerank endpoint (Infinity, no /v1/
//     prefix) — start it with `make infinity-start`.
type RerankConfig struct {
	Provider  string `mapstructure:"provider"`   // "" (disabled) | "openai" | "onnx"
	Model     string `mapstructure:"model"`      // openai: API model id; onnx: registry id (e.g. "gte-reranker-modernbert-base")
	ModelPath string `mapstructure:"model_path"` // onnx only: override the resolved model-cache dir; empty = shared models cache
	BaseURL   string `mapstructure:"base_url"`   // openai only: e.g. "http://127.0.0.1:7997"
	APIKey    string `mapstructure:"api_key"`    // openai only: usually empty for Infinity
	TopK      int    `mapstructure:"top_k"`      // signal-reranked candidates fed to cross-encoder; default 20
	TimeoutMs int    `mapstructure:"timeout_ms"` // per-call deadline in ms; default 3000
}

type EmbeddingConfig struct {
	Provider string `mapstructure:"provider"`
	Model    string `mapstructure:"model"`
	APIKey   string `mapstructure:"api_key"`
	BaseURL  string `mapstructure:"base_url"`
	// BatchSize caps the number of texts per EmbedBatch API call. 0 (default)
	// resolves to 100 inside each provider constructor; values above the
	// provider's documented max are silently clamped down. This is the
	// ceiling, not a demand.
	BatchSize int `mapstructure:"batch_size"`
	// MaxRetries is the number of retry attempts for EmbedBatch calls that
	// receive HTTP 429 (Too Many Requests). Default 3; set to 0 to disable
	// retry entirely. Backoff is exponential with full jitter, capped at 30s;
	// a Retry-After response header overrides the computed delay.
	MaxRetries int `mapstructure:"max_retries"`
	// MaxParallelBatches limits how many EmbedBatch waves execute concurrently.
	// Default 1 (serial). Raise for paid API tiers with real concurrency
	// headroom; keep at 1 for free-tier Gemini or local endpoints.
	MaxParallelBatches int `mapstructure:"max_parallel_batches"`
	// BatchFallback enables per-item Embed() fallback when a batch wave fails
	// with a non-transient HTTP 4xx (not 429) or returns a partial-success 200
	// with some items errored. Default false (opt-in) because the fallback
	// pathologically slows large failing batches (batch_size API calls vs. one).
	BatchFallback bool `mapstructure:"batch_fallback"`
}

type ChunkingConfig struct {
	MaxTokens    int `mapstructure:"max_tokens"`
	OverlapLines int `mapstructure:"overlap_lines"`
	MinTokens    int `mapstructure:"min_tokens"`
}

// OfficeConfig controls DOCX/XLSX/PPTX conversion. XLSXMaxRows / XLSXMaxCols
// bound huge spreadsheet-as-database sheets; IncludeSpeakerNotes toggles
// whether PPTX notes-slide text lands in the generated markdown.
type OfficeConfig struct {
	XLSXMaxRows         int  `mapstructure:"xlsx_max_rows"`
	XLSXMaxCols         int  `mapstructure:"xlsx_max_cols"`
	IncludeSpeakerNotes bool `mapstructure:"include_speaker_notes"`
}

// PDFConfig controls PDF ingestion. MaxPages bounds how many pages the
// handler extracts from a single PDF; 0 means unlimited. Large books with
// thousands of pages can dominate the index otherwise.
type PDFConfig struct {
	MaxPages int `mapstructure:"max_pages"`
}

// SearchConfig controls query-time retrieval behaviour.
type SearchConfig struct {
	// HybridSearch enables BM25 + vector fusion (Reciprocal Rank Fusion) so
	// exact literal matches (e.g. specific identifiers) surface alongside
	// semantic results. Defaults to true; set to false to revert to pure
	// vector search.
	HybridSearch bool `mapstructure:"hybrid_search"`
}

// AnalyticsConfig controls the analytics pass that powers GRAPH_REPORT.md.
type AnalyticsConfig struct {
	// CommunityTimeout bounds the Louvain modularity-optimisation pass.
	// On timeout the communities section of the report is skipped (with a
	// logged warning); god-node analytics, which power the load-bearing
	// sections of GRAPH_REPORT.md, run independently and are unaffected.
	// Default 60s. Set to 0 (or any non-positive value) to disable the bound
	// (legacy unbounded behaviour).
	CommunityTimeout time.Duration `mapstructure:"community_timeout"`
}

// PythonConfig controls Python-specific indexing behaviour. Today only the
// relative-import resolver consumes it; future Python-specific knobs land here.
type PythonConfig struct {
	// SrcRoots lists directories (relative to ProjectRoot) whose immediate
	// children are top-level Python packages. Files under a listed prefix
	// skip the __init__.py walk and anchor at the src_root boundary — covers
	// PEP 420 namespace packages and src-layout projects. Example:
	//   python.src_roots: ["src"]   → src/mypkg/sub/a.py has package mypkg.sub
	//
	// The indexer additionally auto-detects src_roots from pyproject.toml at
	// the project root (setuptools packages.find.where, Poetry packages[].from,
	// and Hatch build.targets.wheel.packages parent dirs). Explicit entries
	// here are merged with auto-detected ones — explicit first, auto-detect
	// appended, deduped on cleaned absolute path.
	//
	// Empty (default) + no pyproject.toml: fall back to __init__.py walk,
	// then a virtual directory package as last resort. Prefixes match after
	// filepath.Clean; src_roots themselves are not recursive — only files
	// under an immediate child of the listed directory are resolved by this
	// rule.
	SrcRoots []string `mapstructure:"src_roots"`
}

// ResolvedDocDirs returns the canonical, cleaned, de-duplicated list of docs
// directories. Precedence:
//   - DocDirs non-empty → use it (DocsDir is ignored).
//   - DocDirs empty, DocsDir non-empty → [DocsDir].
//   - Both empty → ["docs"] (preserves the historic default).
//
// Each entry is passed through filepath.Clean; empty or whitespace-only strings
// are dropped; exact duplicates (post-clean) are removed preserving first-seen
// order.
//
// This method is intentionally PURE — it does NOT reference ProjectRoot (which
// is empty during Load()) and performs no filesystem I/O. Overlap and
// containment validation (which need a root anchor) live in ValidateDocDirs.
func (c *Config) ResolvedDocDirs() []string {
	var raw []string

	if len(c.DocDirs) > 0 {
		raw = c.DocDirs
	} else if c.DocsDir != "" {
		raw = []string{c.DocsDir}
	} else {
		return []string{"docs"}
	}

	// Clean, drop blank entries, and de-duplicate preserving first-seen order.
	seen := make(map[string]bool, len(raw))
	out := make([]string, 0, len(raw))
	for _, entry := range raw {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		cleaned := filepath.Clean(entry)
		if seen[cleaned] {
			continue
		}
		seen[cleaned] = true
		out = append(out, cleaned)
	}

	if len(out) == 0 {
		return []string{"docs"}
	}
	return out
}

// ValidateDocDirs validates the resolved doc_dirs for structural correctness.
// It operates on ResolvedDocDirs() and performs two checks:
//
//  1. Overlap rejection — rejects configurations where one dir is a
//     path-ancestor of another (e.g. ["docs", "docs/api"]). Such a pair
//     produces stored file_path collisions because WalkDocs uses the dir
//     name as the path prefix. The check is segment-aware (uses filepath.Rel)
//     so sibling names like "docs" and "docs-api" are correctly treated as
//     independent (NOT flagged).
//
//  2. Containment check — when projectRoot is non-empty, each entry is
//     resolved as filepath.Join(projectRoot, entry) and the resulting absolute
//     path is confirmed to lie within projectRoot via filepath.Rel. An entry
//     that starts with ".." or is an absolute path outside projectRoot is
//     rejected. When projectRoot is "" (standalone/test flows) this check is
//     skipped — the overlap check still runs.
//
// Non-existent directories are NOT rejected here; callers may warn+skip them
// during indexing. This function performs no filesystem I/O (no os.Stat).
//
// Returns a descriptive error listing all offending pairs/dirs, or nil.
func (c *Config) ValidateDocDirs(projectRoot string) error {
	if projectRoot != "" {
		projectRoot = filepath.Clean(projectRoot)
	}
	dirs := c.ResolvedDocDirs()
	var errs []string

	// --- Overlap check (segment-aware) ---
	// For every pair (i, j), check whether j is a descendant of i or vice
	// versa. filepath.Rel(a, b) returns a path starting with ".." when b is
	// NOT under a, so we can use that as the discriminator. The check must be
	// symmetric: also test Rel(b, a).
	for i := 0; i < len(dirs); i++ {
		for j := i + 1; j < len(dirs); j++ {
			a, b := dirs[i], dirs[j]
			if isAncestor(a, b) {
				errs = append(errs, fmt.Sprintf(
					"doc_dirs overlap: %q is an ancestor of %q — use non-overlapping directories to avoid file_path collisions",
					a, b,
				))
			} else if isAncestor(b, a) {
				errs = append(errs, fmt.Sprintf(
					"doc_dirs overlap: %q is an ancestor of %q — use non-overlapping directories to avoid file_path collisions",
					b, a,
				))
			}
		}
	}

	// --- Containment check (only when projectRoot is known) ---
	if projectRoot != "" {
		absRoot := filepath.Clean(projectRoot)
		for _, dir := range dirs {
			// If dir is already absolute, use it as-is; otherwise join under
			// the workspace root. filepath.Join silently drops preceding
			// components when a later element is absolute, which would let an
			// absolute path bypass the rel check — so we detect that case
			// explicitly here.
			var absDir string
			if filepath.IsAbs(dir) {
				absDir = filepath.Clean(dir)
			} else {
				absDir = filepath.Join(absRoot, dir)
			}
			rel, err := filepath.Rel(absRoot, absDir)
			if err != nil || strings.HasPrefix(rel, "..") || filepath.IsAbs(rel) {
				errs = append(errs, fmt.Sprintf(
					"doc_dirs entry %q resolves outside the workspace root %q — only paths within the workspace are allowed",
					dir, projectRoot,
				))
			}
		}
	}

	if len(errs) > 0 {
		return errors.New(strings.Join(errs, "; "))
	}
	return nil
}

// isAncestor reports whether candidate is a strict path ancestor of target.
// It uses filepath.Rel so that "docs" is an ancestor of "docs/api" but
// "docs-api" is NOT an ancestor of "docs-api/sub" relative to "docs".
// Both inputs must already be filepath.Clean'd.
func isAncestor(candidate, target string) bool {
	rel, err := filepath.Rel(candidate, target)
	if err != nil {
		return false
	}
	// Rel returns "." when candidate == target (handled by de-dup already),
	// starts with ".." when target is not under candidate, or a clean
	// relative sub-path when it IS under candidate.
	return rel != "." && !strings.HasPrefix(rel, "..")
}

func Load() *Config {
	cfg := &Config{
		DocsDir: "docs",
		DBPath:  ".librarian/librarian.db",
		Embedding: EmbeddingConfig{
			Provider:   "gemini",
			MaxRetries: 3,
		},
		Chunking: ChunkingConfig{
			MaxTokens:    512,
			OverlapLines: 3,
			MinTokens:    50,
		},
		Office: OfficeConfig{
			XLSXMaxRows:         100,
			XLSXMaxCols:         50,
			IncludeSpeakerNotes: true,
		},
		PDF: PDFConfig{
			MaxPages: 0,
		},
		Graph: GraphConfig{
			Enabled:         true,
			HonorGitignore:  true,
			DetectGenerated: true,
			TestEdges:       TestEdgesConfig{Enabled: true},
		},
		Search: SearchConfig{
			HybridSearch: true,
		},
		Analytics: AnalyticsConfig{
			CommunityTimeout: 60 * time.Second,
		},
		CodeFilePatterns: []string{"*.go", "*.ts", "*.py", "*.rs", "*.java", "*.rb"},
		ExcludePatterns:  []string{"node_modules/**", ".git/**", "vendor/**", ".claude/worktrees/**", ".claude/agents/**", ".claude/skills/**"},
	}

	viper.Unmarshal(cfg)

	// Restore bool defaults for GraphConfig after Unmarshal. If the user's
	// config.yaml has a `graph:` section that omits these keys, mapstructure
	// decodes the absent value as `false` and clobbers the `true` default
	// we set above. Each IsSet check reinstates the default when the user
	// didn't express an opinion.
	if !viper.IsSet("graph.enabled") {
		cfg.Graph.Enabled = true
	}
	if !viper.IsSet("graph.honor_gitignore") {
		cfg.Graph.HonorGitignore = true
	}
	if !viper.IsSet("graph.detect_generated") {
		cfg.Graph.DetectGenerated = true
	}
	if !viper.IsSet("search.hybrid_search") {
		cfg.Search.HybridSearch = true
	}
	if !viper.IsSet("graph.test_edges.enabled") {
		cfg.Graph.TestEdges.Enabled = true
	}
	if !viper.IsSet("embedding.max_retries") {
		cfg.Embedding.MaxRetries = 3
	}
	if !viper.IsSet("embedding.max_parallel_batches") {
		cfg.Embedding.MaxParallelBatches = 1
	}
	// Restore duration default for AnalyticsConfig after Unmarshal. If the
	// user's config.yaml has an `analytics:` section that omits this key,
	// mapstructure decodes the absent value as 0 and clobbers the default
	// we set above. The IsSet check reinstates the default when the user
	// didn't express an opinion (0 is a valid explicit "disabled" value).
	if !viper.IsSet("analytics.community_timeout") {
		cfg.Analytics.CommunityTimeout = 60 * time.Second
	}

	// Always-on Claude Code ephemera patterns. These accumulate transient files
	// (agent worktrees, generated agent specs, vendored skills) that would pollute
	// the index regardless of how the user has set exclude_patterns. Merge them
	// in even when the user config explicitly overrides the slice.
	claudeAlwaysExcludes := []string{
		".claude/worktrees/**",
		".claude/agents/**",
		".claude/skills/**",
	}
	present := make(map[string]bool, len(cfg.ExcludePatterns))
	for _, p := range cfg.ExcludePatterns {
		present[p] = true
	}
	for _, p := range claudeAlwaysExcludes {
		if !present[p] {
			cfg.ExcludePatterns = append(cfg.ExcludePatterns, p)
		}
	}

	if dbPath := viper.GetString("db_path"); dbPath != "" {
		cfg.DBPath = dbPath
	}

	// Fall back to default if no db_path was set via config, env, or flag
	if cfg.DBPath == "" {
		cfg.DBPath = ".librarian/librarian.db"
	}

	return cfg
}
